/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreaturesImport } from './routes/creatures'
import { Route as BoostableBossesImport } from './routes/boostable-bosses'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreaturesRoute = CreaturesImport.update({
  id: '/creatures',
  path: '/creatures',
  getParentRoute: () => rootRoute,
} as any)

const BoostableBossesRoute = BoostableBossesImport.update({
  id: '/boostable-bosses',
  path: '/boostable-bosses',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boostable-bosses': {
      id: '/boostable-bosses'
      path: '/boostable-bosses'
      fullPath: '/boostable-bosses'
      preLoaderRoute: typeof BoostableBossesImport
      parentRoute: typeof rootRoute
    }
    '/creatures': {
      id: '/creatures'
      path: '/creatures'
      fullPath: '/creatures'
      preLoaderRoute: typeof CreaturesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boostable-bosses': typeof BoostableBossesRoute
  '/creatures': typeof CreaturesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boostable-bosses': typeof BoostableBossesRoute
  '/creatures': typeof CreaturesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/boostable-bosses': typeof BoostableBossesRoute
  '/creatures': typeof CreaturesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boostable-bosses' | '/creatures'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boostable-bosses' | '/creatures'
  id: '__root__' | '/' | '/boostable-bosses' | '/creatures'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoostableBossesRoute: typeof BoostableBossesRoute
  CreaturesRoute: typeof CreaturesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoostableBossesRoute: BoostableBossesRoute,
  CreaturesRoute: CreaturesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/boostable-bosses",
        "/creatures"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/boostable-bosses": {
      "filePath": "boostable-bosses.tsx"
    },
    "/creatures": {
      "filePath": "creatures.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
